---
title: "Publication"

---
Lingkungan Pembangunan SDM Sektor Industri melalui Pendidikan Vokasi
IML Vierke
PROSIDING Seminar Nasional FKIP Universitas Muslim Maros 1, 35-43	5	2019


Analysis of Fiscal Incentive Policies in The Electronic Industries Using Regulatory Impact Analysis (RIA)
IML Vierke, D Budhi, A Sanusi, S Ahmar
Journal of Scientific Research, Education, and Technology (JSRET) 2 (1), 288-306	3	2023


Analisis Efektivitas Program Fasilitasi Penumbuhan Wirausaha Baru Di Pondok Pesantren
R Kurniawati, I Dharmayanti, IM Lewiayu, E Pratomo, B Hartono
Prosiding Seminar Nasional Manajemen Industri dan Rantai Pasok 1 (1), 47-55	3	2020


Analisis Struktural Interpretatif untuk Merancang Transformasi Digital Pendidikan Tinggi di Indonesia
IML Vierke, R Syarief, I Fahmi, I Sailah
Equilibrium: Jurnal Pendidikan 12 (1), 90-101	2	2024


Analisis Intra Industry Trade Pada Industri Refrigerators Pada 10 Partner Dagang Indonesia
IML Virke, S Ahmar, A Sanusi
Prosiding Seminar Nasional Manajemen Industri dan rantai Pasok 4 (1), 27-34	1	2023


Analisis Penerapan Kebijakan Insentif Fiskal Industri Elektronika
IML Vierke, D Budhi, A Sanusi, S Ahmar
Prosiding Seminar Nasional Manajemen Industri dan Rantai Pasok 3 (1), 245-257	1	2022


Development of Export-Oriented Smes Through the Implementation of Client Relationship Management (CRM)
IML Vierke, F Ibrahim
International Journal of Sustainable Social Science (IJSSS) 2 (No.2,2024 …		2024


Import Substitution in Circular Economy Perspective: A Study on Textile And Apparel Industry
S Nurkomariyah, IML Vierke
International Journal of Social Science And Human Research 6 (12 December …		2023


Enhancing Economic Growth through BMDTP Policy Interventions in the Electronics Industry
IM Vierke, S Ahmar, A Sanusi
Proceedings of the 6th International Conference of Economics, Business, and …		2023


The Electronic Industry Intra-Industry Trade Analysis in 10 Indonesian Trading Partners: Case Study: Refrigerator Products
I Vierke, S Ahmar, A Sanusi
Journal of Scientific Research, Education, and Technology (JSRET) 2 (4 …		2023


Comprehensive Framework for Addressing the Challenges of Technology-Enhanced Learning (TEL)
IML Vierke, R Syarief, I Fahmi, I Sailah
International Journal of Social Science And Human Research 6, 5519-5526		2023


Dampak Pandemi Covid-19 Terhadap Kinerja Ekspor Produk Alas Kaki
SA A Sanusi, IML Vierke
Prosiding Seminar Nasional Manajemen Industri dan Rantai Pasok 2nd, Jakarta …